version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: go-db-container
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: goDB
  app:
    build: .
    container_name: go-app-container
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=goDB
    depends_on:
      - db
    restart: always
